Controllers/Home4adminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RMVC_GHandbook.Data;
using RMVC_GHandbook.Models;
using System.Diagnostics;
using System.Text.RegularExpressions;

namespace RMVC_GHandbook.Controllers
{
    // объявляем контроллер который будет обрабатывать запросы и возвращать представления 
    public class Home4adminController : Controller
    {
        // создаем средство ведения журнала для Home4adminController
        private readonly ILogger<HomeController> _logger;
        // создаем средство обращения к базе данных
        private readonly ApplicationDBContext _db;
        // вызываем созданные средства
        public Home4adminController(ILogger<HomeController> logger, ApplicationDBContext db)
        {
            _logger = logger;
            _db = db;
        }
        // генератор стартовой страницы index которая возвращает список видеоигр и их параметры
        public IActionResult Index(string? search)
        {
            // создаем список char которые фильтруются из запросов
            var dd = new char[] {'/','"','\'' };
            // получаем данные из базы данных как нумерованный массив
            IEnumerable<GameMasterClass> ObjGamesList = _db.Games.ToList();
            // если запрос не сожержит фильтров (пустой) возвращаем все данные
            if (search == null)
			{
                return View(ObjGamesList);
            }
            // убираем лишние символы из запроса
            search = search.Trim(dd);
            // создаем новый список данных
            List<GameMasterClass> resultr = new List<GameMasterClass>();
            // для каждого элемента из базы данных проверяем на совпадения с фильтрами
            foreach (var item in ObjGamesList)
			{
                // если итем соответствует фильтру, сохраняем в новый массив
                if (item.Title.ToLower().Contains(search.ToLower()) || item.Genre.ToLower().Contains(search.ToLower()))
				{
                    resultr.Add(item);
                }	
			}
            // возвращаем новый массив данных
            return View(resultr);
        }
		// генератор страницы create реализующий форму сбора данных
		public IActionResult Create()
		{
			return View();
		}
		// обрабатываем данные из формы create и ссохраняем из в базу данных
		//POST
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(GameMasterClass obj)
		{
            // получаем данные из базы данных как нумерованный массив
            IEnumerable<GameMasterClass> ObjGamesList = _db.Games.ToList();
			// для каждогоэлемента массива проверим существование элементов
            foreach (var item in ObjGamesList)
            {
				if (obj.Title.ToLower() == item.Title.ToLower()){ ModelState.AddModelError("Title","Already exists");}
			}
			// проверим является ли модель правильной и достаточной
            if (ModelState.IsValid)
			{
				// если указан жанр преобразуем символы в нижний регистр
                if (obj.Genre != null)
                {
                    obj.Genre = obj.Genre.ToLower();
                }
				// добавим данные в нумерованный массив
				_db.Games.Add(obj);
				// сохраним изменения в базе данных
				_db.SaveChanges();
				// добавим кастомный вывод сообщающий об успехе
				TempData["success"] = "Game created successfully";
				// перенаправим пользователя на стартовую страницу 
				return RedirectToAction("Index");
			}
			// в остальных случаях вернем модель (набор ошибок валидации)
			return View(obj);
		}
        // генератор страницы edit реализующий форму сбора данных для уже существующего элемента базы данных
        //GET
        public IActionResult Edit(int? id)
		{
			// если элемент не задан возвращаем "не найдено"
			if (id == null || id == 0)
			{
				return NotFound();
			}
			// получаем первый или дефолтный элемент из базы данных соответствующий id
			var gameFromDb = _db.Games.FirstOrDefault(u=>u.Id==id);
			// если элемент не найден в базе данных возвращаем "не найдено"
			if (gameFromDb == null)
			{
				return NotFound();
			}
			// возвращаем форму для текущего элемента
			return View(gameFromDb);
		}
        // обрабатываем данные из формы edit и сохраняем их в базу данных
        //POST
        [HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(GameMasterClass obj)
		{
            // проверим является ли модель правильной и достаточной
            if (ModelState.IsValid)
			{
                // если указан жанр преобразуем символы в нижний регистр
                if (obj.Genre != null)
				{
					obj.Genre = obj.Genre.ToLower();
				}
                // изменяем данные в нумерованном массиве
                _db.Games.Update(obj);
                // сохраним изменения в базе данных
                _db.SaveChanges();
                // добавим кастомный вывод сообщающий об успехе
                TempData["success"] = "Game updated successfully";
                // перенаправим пользователя на стартовую страницу 
                return RedirectToAction("Index");
			}
            // в остальных случаях вернем модель (набор ошибок валидации)
            return View(obj);
		}
        // генератор страницы edit реализующий форму сбора данных для уже существующего элемента базы данных
        public IActionResult Delete(int? id)
		{
            // если элемент не задан возвращаем "не найдено"
            if (id == null || id == 0)
			{
				return NotFound();
			}
            // получаем первый или дефолтный элемент из базы данных соответствующий id
            var gameFromDb = _db.Games.FirstOrDefault(u=>u.Id==id);
            // если элемент не найден в базе данных возвращаем "не найдено"
            if (gameFromDb == null)
			{
				return NotFound();
			}
            // возвращаем форму для текущего элемента
            return View(gameFromDb);
		}
        // обрабатываем данные из формы delete и сохраняем их в базу данных
        //POST
        [HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public IActionResult DeletePOST(int? id)
		{
            // получаем первый или дефолтный элемент из базы данных соответствующий id
            var obj = _db.Games.FirstOrDefault(u=>u.Id==id);
            // если элемент не найден в базе данных возвращаем "не найдено"
            if (obj == null)
			{
				return NotFound();
			}
            // удаляем данные в нумерованном массиве
            _db.Games.Remove(obj);
            // сохраним изменения в базе данных
            _db.SaveChanges();
            // добавим кастомный вывод сообщающий об успехе
            TempData["success"] = "Game deleted successfully";
            // перенаправим пользователя на стартовую страницу 
            return RedirectToAction("Index");
		}
        // генератор страницы возвращающей все данные для конкретного итема
        public async Task<IActionResult> Details(int? id)
		{
            // если итема не существует возвращаем "не найдено"
            if (id == null || _db.Games == null)
            {
                return NotFound();
			}
            // находим первый или дефолтный результат из базы данных соответствующий id
            var gameMasterClass = await _db.Games
                .FirstOrDefaultAsync(m => m.Id == id);
            // если итема нет в базе данных возвращаем "не найдено"
            if (gameMasterClass == null)
            {
                return NotFound();
            }
            // в остальных случаях возвращаем итем
            return View(gameMasterClass);
        }
        // генератор страницы ошибок
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home4admin/Create.cshtml
<!--
    Представление которому обращается Home4adminController Create
-->
<!-- укажем GameMasterClass как базовою модель -->
@model GameMasterClass
<!--создадим форму сбора данных для нашей модели-->
<form method="post">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Create Category</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Title"></label>
			<input asp-for="Title" class="form-control" />
			<span asp-validation-for="Title" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="TiDescription"></label>
			<input asp-for="TiDescription" class="form-control" />
			<span asp-validation-for="TiDescription" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ReleaseDate"></label>
			<input asp-for="ReleaseDate" class="form-control" />
			<span asp-validation-for="ReleaseDate" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Genre"></label>
			<input asp-for="Genre" class="form-control" />
			<span asp-validation-for="Genre" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Price"></label>
			<input asp-for="Price" class="form-control" />
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<!--создадим кнопку которая будет передавать значения формы в метод контроллера Create POST для дальнейшей обработки-->
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<!--создадим кнопку возвращающую пользователя на страницу Index-->
		<a asp-controller="Home4admin" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>
<!--вызовем базовый скрипт валидации данных для созданной формы-->
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Views/Home4admin/Delete.cshtml
<!--
    Представление которому обращается Home4adminController Delete
-->
<!-- укажем GameMasterClass как базовою модель -->
@model GameMasterClass
<!--создадим форму сбора данных для нашей модели так как мы получаем конкретную модель уже имеюую значеиня,
форма уже будет иметь заполненные поля и заполнять их отдельно не понадобится-->
<form method="post" asp-action="Delete">
	<input asp-for="Id" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Category</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Title"></label>
			<input asp-for="Title" class="form-control" />
			<span asp-validation-for="Title" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="TiDescription"></label>
			<input asp-for="TiDescription" class="form-control" />
			<span asp-validation-for="TiDescription" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ReleaseDate"></label>
			<input asp-for="ReleaseDate" class="form-control" />
			<span asp-validation-for="ReleaseDate" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Genre"></label>
			<input asp-for="Genre" class="form-control" />
			<span asp-validation-for="Genre" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Price"></label>
			<input asp-for="Price" class="form-control" />
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<!--создадим кнопку которая будет передавать значения формы в метод контроллера Delete POST для дальнейшей обработки-->
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<!--создадим кнопку возвращающую пользователя на страницу Index-->
		<a asp-controller="Home4admin" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>
<!--вызовем базовый скрипт валидации данных для созданной формы-->
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Views/Home4admin/Details.cshtml
<!--
    Представление которому обращается Home4adminController Details
-->
<!-- укажем GameMasterClass как базовою модель -->
@model RMVC_GHandbook.Models.GameMasterClass
@{
    ViewData["Title"] = "Details";
}
<!-- Разметим страницу -->
<h1>Details</h1>
<div>
    <h4>GameMasterClass</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <!--используем метод DisplayNameFor для получения название колонки таблицы-->
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            <!--используем метод DisplayFor для получения значение колонки таблицы-->
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TiDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TiDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AddDate)
        </dd>
    </dl>
</div>
<div>
    <!--создадим кнопку для переадресации пользователя на страницу Edit для текущего итема-->
    <a asp-controller="Home4admin" asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
    <!--создадим кнопку для переадресации пользователя на страницу Index-->
    <a asp-controller="Home4admin" asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Views/Home4admin/Edit.cshtml
<!--
    Представление которому обращается Home4adminController Delete
-->
<!-- укажем GameMasterClass как базовою модель -->
@model GameMasterClass
<!--создадим форму сбора данных для нашей модели так как мы получаем конкретную модель уже имеюую значеиня,
форма уже будет иметь заполненные поля и заполнять их отдельно не понадобится-->
<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Data</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="Title"></label>
			<input asp-for="Title" class="form-control" />
			<span asp-validation-for="Title" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="TiDescription"></label>
			<input asp-for="TiDescription" class="form-control" />
			<span asp-validation-for="TiDescription" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="ReleaseDate"></label>
			<input asp-for="ReleaseDate" class="form-control" />
			<span asp-validation-for="ReleaseDate" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Genre"></label>
			<input asp-for="Genre" class="form-control" />
			<span asp-validation-for="Genre" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="Price"></label>
			<input asp-for="Price" class="form-control" />
			<span asp-validation-for="Price" class="text-danger"></span>
		</div>
		<!--создадим кнопку которая будет передавать значения формы в метод контроллера Edit POST для дальнейшей обработки-->
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<!--создадим кнопку для переадресации пользователя на страницу Index для текущего итема-->
		<a asp-controller="Home4admin" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>
<!--вызовем базовый скрипт валидации данных для созданной формы-->
@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

Views/Home4admin/Index.cshtml
<!--
    Представление которому обращается Home4admin Controller Index
-->
<!-- GameMasterClass указан как базовою модель в коде контроллера, так что объявлять его и здесь не требуется-->
@{
    ViewData["Title"] = "Games Page";
}
<!-- Разметим страницу -->
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Game List</h2>
		</div>
        <div class="col-6 text-end">
            <a asp-controller="Home4admin" asp-action="Create" class="btn btn-primary">
               <i class="bi bi-plus-circle"></i> &nbsp; Store New One
			</a>
		</div>
	</div>
    <br /><br />
<!--Зададим колонки таблицы в ручную-->
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                Game
            </th>
            <th>    
                Description
            </th>
            <th>
                Genre
            </th>
            <th>
                Price
            </th>
        </tr>
    </thead>
    <tbody>
        <!--Используем возможности шаблонизатора ис помощью цикла пройдем по значениям переданым в представление, чтобы заполнить таблицу-->
        <!--Вызов кода и обращения к переменным требуют указания для шаблонизатора методом at-->
        @foreach (var item in Model)
        {
            <tr>
                <th>
                    @item.Title
                </th>
                <th>
                    @item.TiDescription
                </th>
                <th>
                    @item.Genre
                </th>
                <th>
                    @item.Price
                </th>
            
                <td>
                    <div class="w-75 btn-group" role="group">
                       <!--Создадим для каждого элемента кнопку, которая перенесет пользователя на представление Details соответствующее выбранному элементу-->
                            <a asp-controller="Home4admin" asp-action="Details" asp-route-id="@item.Id"
                       class="btn btn-primary mx-2">Details</a>
                       <!--Создадим для каждого элемента кнопку, которая перенесет пользователя на представление Edit соответствующее выбранному элементу-->
                            <a asp-controller="Home4admin" asp-action="Edit" asp-route-id="@item.Id"
                       class="btn btn-primary mx-2"> <i class="bi bi-pencil-square"></i> Edit</a>
                       <!--Создадим для каждого элемента кнопку, которая перенесет пользователя на представление Delete соответствующее выбранному элементу-->
                            <a asp-controller="Home4admin" asp-action="Delete" asp-route-id="@item.Id"
                       class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>